To string
duckth/bdsa-project-newgit pull request #21
Opened 2022-11-03 11:35 UTC by Lucasfth

2022-11-03 12:02 UTC, fredpetersen requested changes
Enkelte kommentarer, vent evt. med at merge til i morgen så vi kan få snakket om det sidste :)

2022-11-03 12:02 UTC, fredpetersen commented on NEWgIT.Tests/CommitLog.cs
> +public static class CommitLog
Tror stadig jeg ville have Extension i navnet, da filen jo ikke indeholder en commitlog, men extension til en repository type
navnet kunne eksempelvis være RepositoryExtensions?

2022-11-03 12:19 UTC, Lucasfth commented on NEWgIT.Tests/CommitLog.cs
> +public static class CommitLog
Jeg har lavet den om igen. Jeg glemte at jeg havde omnavngivet den. Det var et artikfakt af en anden ændring som er fjernet.

2022-11-03 12:21 UTC, Lucasfth commented on NEWgIT.Tests/CommitCounterTests.cs
> -        result[new DateOnly(2019, 5, 25)].Should().Be(3);
Tror det var en fejl Den er også tilføjet igen.

2022-11-04 12:22 UTC, Lucasfth commented on NEWgIT.Tests/StringifyTests.cs
> +        _remove = "[" + String.Concat(chars) + "]";
K

2022-11-04 12:36 UTC, fredpetersen approved these changes
good enough 👍

2022-11-04 12:37 UTC, merged