feature/azure auth
duckth/bdsa-project-newgit pull request #87
Opened 2022-11-30 18:06 UTC by duckth

- add lots of sample stuff
- convert client go wasm
- remove sample
- add functional auth

2022-11-30 18:12 UTC, duckth commented on NEWgIT.Client/NEWgIT.Client.csproj
> +    <_ContentIncludedByDefault Remove="wwwroot\sample-data\weather.json" />
slet

2022-11-30 18:12 UTC, duckth commented on NEWgIT.Client/Pages/FetchData.razor
> +{
slet hele siden

2022-11-30 18:12 UTC, duckth commented on NEWgIT.Client/Pages/Index.razor
> +    public record FrequenciesDTO(Dictionary<DateOnly, int> Frequencies);
for at undgå dependency på Newgit.Core - vi må lige overveje hvad der er det "rigtige" at gøre

2022-11-30 18:12 UTC, duckth commented on NEWgIT.Client/Shared/NavMenu.razor
> +        <a class="navbar-brand" href="">BlazorSample</a>
slet hele siden

2022-11-30 18:12 UTC, duckth commented on NEWgIT.Client/Shared/NavMenu.razor
> +        <a class="navbar-brand" href="">BlazorSample</a>
medmindre vi bruger den?

2022-11-30 18:12 UTC, duckth commented on NEWgIT.Client/wwwroot/appsettings.json
> +    "ClientId": "3c893c1f-4f13-4b01-ade1-442988ed6c23",
burde det her være i secrets? hmm..

2022-11-30 18:12 UTC, duckth commented on NEWgIT.Client/wwwroot/css/app.css
>  }
Den her fil er fuldstændig kaos - jeg tror det virker though

2022-11-30 18:12 UTC, duckth commented on NEWgIT.Client/wwwroot/css/open-iconic/README.md
> +[Open Iconic v1.1.1](https://github.com/iconic/open-iconic)
nok bare slet

2022-11-30 18:23 UTC, fredpetersen requested changes

2022-11-30 18:23 UTC, fredpetersen commented on NEWgIT.Client/Pages/Counter.razor
> +﻿@page "/counter"
🗡️ hele siden

2022-11-30 18:23 UTC, fredpetersen commented on NEWgIT.Client/Pages/FetchData.razor
> +﻿@page "/fetchdata"
🗡️ hele siden

2022-11-30 18:23 UTC, fredpetersen commented on NEWgIT.Client/Program.cs
> +var api_scope = @"https://newgitb2c.onmicrosoft.com/newgit-api/access_as_user";
Dette er vel kun auth_scope? Eller misforstår jeg?

2022-11-30 18:23 UTC, fredpetersen commented on NEWgIT.Client/wwwroot/css/open-iconic/README.md
> +[Open Iconic v1.1.1](https://github.com/iconic/open-iconic)
Hvad er det her?
Kan det også bare 🗡️ ?

2022-11-30 18:24 UTC, fredpetersen commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=duckth_bdsa-project-newgit&pullRequest=87)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=SECURITY_HOTSPOT) [![E](https://camo.githubusercontent.com/ca3e5c9e7ad5fd04244d2d793976efbe479a024b145a815384556548a9884b5f/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=CODE_SMELL) [2 Code Smells](https://sonarcloud.io/project/issues?id=duckth_bdsa-project-newgit&pullRequest=87&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=duckth_bdsa-project-newgit&pullRequest=87&metric=coverage&view=list) No Coverage information [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=duckth_bdsa-project-newgit&pullRequest=87&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=duckth_bdsa-project-newgit&pullRequest=87&metric=new_duplicated_lines_density&view=list)

Kan være du også lige skal have styr på det der security hotspot før den merges

2022-11-30 21:02 UTC, duckth commented on NEWgIT.Client/wwwroot/css/open-iconic/README.md
> +[Open Iconic v1.1.1](https://github.com/iconic/open-iconic)
Jeg ved ikke hvad det er
Tror det er med som default?

2022-12-02 11:43 UTC, lucasfth approved these changes
looks good

2022-12-02 11:50 UTC, merged